Repository chutney-testing/chutney, pull requests merged in 2023-07, with the labels that each got.

#1081 fix(environment) : check that all targets are unique before saving
  environment/src/main/java/com/chutneytesting/environment/domain/Target.java
  environment/src/main/java/com/chutneytesting/environment/domain/exception/TargetAlreadyExistsException.java
  environment/src/main/java/com/chutneytesting/environment/infra/JsonFilesEnvironmentRepository.java
  environment/src/test/java/com/chutneytesting/environment/infra/JsonFilesEnvironmentRepositoryTest.java
Labels: technical

#1082 fix(target) : fix url regex to include numbers, +, - and . in the protocol section
  ui/src/app/molecules/validation/validation.service.spec.ts
  ui/src/app/molecules/validation/validation.service.ts
Labels: technical

#1069 fix(ui): fix target properties edition
  ui/src/app/modules/target/details/target.component.html
  ui/src/app/modules/target/details/target.component.ts
  ui/src/app/modules/target/list/targets.component.html
  ui/src/app/modules/target/list/targets.component.scss
  ui/src/app/modules/target/list/targets.component.ts
  ui/src/app/molecules/panel/property-table-panel/property-table-panel.component.ts
Labels: bug

#1083 Remove complex object from action input
  action-impl/src/main/java/com/chutneytesting/action/jms/JmsActionParameter.java
  action-impl/src/main/java/com/chutneytesting/action/jms/JmsCleanQueueAction.java
  action-impl/src/main/java/com/chutneytesting/action/jms/JmsConnectionFactory.java
  action-impl/src/main/java/com/chutneytesting/action/jms/JmsListenerAction.java
  action-impl/src/main/java/com/chutneytesting/action/jms/consumer/ConsumerFactory.java
  action-impl/src/main/java/com/chutneytesting/action/jms/consumer/JmsListenerParameters.java
  action-impl/src/main/java/com/chutneytesting/action/jms/domain/XmlContent.java
  action-impl/src/test/java/com/chutneytesting/action/jms/JmsCleanQueueActionTest.java
  action-impl/src/test/java/com/chutneytesting/action/jms/JmsListenerActionTest.java
  action-impl/src/test/java/com/chutneytesting/action/jms/consumer/ConsumerFactoryTest.java
  engine/src/main/java/com/chutneytesting/action/api/ActionDto.java
  engine/src/main/java/com/chutneytesting/action/api/ActionTemplateMapper.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/parameterResolver/InputParameterResolver.java
  engine/src/test/java/com/chutneytesting/action/api/ActionControllerTest.java
  engine/src/test/java/com/chutneytesting/action/api/ActionTemplateMapperTest.java
  engine/src/test/java/com/chutneytesting/action/api/ComplexParameterTestClass.java
  engine/src/test/java/com/chutneytesting/action/api/EmbeddedActionEngineTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/parameterResolver/ComplexObjectConstructor.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/parameterResolver/InputParameterResolverTest.java
Labels: technical

#1037 fix(server): save campaign - scenario link at scenario execution end
  server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ExecutionRequest.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
  server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  ui/src/app/core/model/campaign/campaign-execution-report.model.ts
  ui/src/app/modules/campaign/components/execution/history/campaign-executions-history.component.ts
Labels: enhancement
