Repository chutney-testing/chutney, pull requests merged in 2023-11, with the labels that each got.

#1171 chore: Remove last orient dependency
  GETTING_STARTED.md
  packaging/local-api-unsecure/src/main/resources/logback.xml
  packaging/local-dev/src/main/resources/logback.xml
  pom.xml
  ui/src/app/modules/database-admin/components/database-admin.component.html
Labels: technical

#1178 chore(): release 2.4.0
  CHANGELOG.md
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1179 chore(): prepare next dev version (2.4.1-SNAPSHOT)
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1180 bugfix: empty report and info/error style
  ui/src/app/core/model/scenario/scenario-execution-report.model.ts
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.html
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.scss
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
  ui/src/app/modules/scenarios/services/scenario-execution.service.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: bug
