Repository chutney-testing/chutney, pull requests merged in 2023-03, with the labels that each got.

#1015 tech(engine): Rename Action pause/resume/stop as Command
  engine/src/main/java/com/chutneytesting/engine/domain/execution/ExecutionManager.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/ScenarioExecution.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/command/PauseExecutionCommand.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/command/ResumeExecutionCommand.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/command/StopExecutionCommand.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/ScenarioExecutionTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/step/StepTest.java
Labels: technical

#1017 Fix/UI bug
  ui/src/app/core/components/login/login.component.ts
  ui/src/app/shared/alert.service.ts
  ui/src/app/shared/components/chutney-editor/chutney-editor.component.ts
  ui/src/assets/style/layout/header/_header-base.scss
  ui/src/assets/style/layout/sidebar/_sidebar-base.scss
  ui/src/assets/style/layout/sidebar/modifiers/_closed-sidebar.scss
Labels: bug

#1022 feat(ui): + sort scenarios on campaign execution report
  ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.html
  ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.ts
Labels: enhancement

#1021 Step iterations dataset
  component/src/main/java/com/chutneytesting/component/execution/domain/ComposedTestCaseDatatableIterationsPreProcessor.java
  engine/src/main/java/com/chutneytesting/engine/domain/delegation/RemoteStepExecutor.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/DefaultStepExecutor.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/StepExecutor.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/evaluation/StepDataEvaluator.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/scenario/StepBuilder.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/step/Step.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/step/StepContext.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/report/StepExecutionReport.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/DataSetIterationsStrategy.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/DefaultStepExecutionStrategy.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/RetryWithTimeOutStrategy.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/SoftAssertStrategy.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/StepExecutionStrategy.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/StepIterationStrategy.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/StepStrategyDefinition.java
  engine/src/main/java/com/chutneytesting/engine/domain/report/Reporter.java
  engine/src/main/resources/META-INF/extension/chutney.strategies
  engine/src/test/java/com/chutneytesting/ExecutionConfigurationTest.java
  engine/src/test/java/com/chutneytesting/action/TestActionTemplateFactory.java
  engine/src/test/java/com/chutneytesting/engine/api/execution/HttpTestEngineTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/delegation/RemoteStepExecutorTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/DefaultExecutionEngineTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/DefaultStepExecutorTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/step/StepTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/DefaultStepExecutionStrategyTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/RetryWithTimeOutStrategyTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/SoftAssertStrategyTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/StepIterationStrategyTest.java
  engine/src/test/java/com/chutneytesting/tools/Jsons.java
  engine/src/test/resources/META-INF/extension/chutney.actions
  engine/src/test/resources/META-INF/extension/chutney.strategies
  engine/src/test/resources/scenarios_examples/simple_step_iterations.json
  engine/src/test/resources/scenarios_examples/simple_step_iterations_fail_at_end.json
  engine/src/test/resources/scenarios_examples/step_iterations_using_data_from_context.json
  engine/src/test/resources/scenarios_examples/step_iterations_with_parent_and_substeps.json
  server/src/test/resources/blackbox/engine/context.feature
Labels: enhancement
