Repository chutney-testing/chutney, pull requests merged in 2023-12, with the labels that each got.

#1191 chore(ui): Bump nodejs from 16.19.1 to 20.10.0
  .env.nix
  ui/package-lock.json
  ui/pom.xml
Labels: technical

#1190 fix(): Fix icon "NOT_EXECUTED" for execution history
  ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.html
Labels: bug

#1193 Does not display action button and report if scenario was not …
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.html
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
Labels: bug

#1177 Feature/add proxy jira
  jira/pom.xml
  jira/src/main/java/com/chutneytesting/jira/api/JiraConfigurationDto.java
  jira/src/main/java/com/chutneytesting/jira/api/JiraModuleController.java
  jira/src/main/java/com/chutneytesting/jira/domain/JiraTargetConfiguration.java
  jira/src/main/java/com/chutneytesting/jira/infra/HttpJiraXrayImpl.java
  jira/src/main/java/com/chutneytesting/jira/infra/JiraFileRepository.java
  jira/src/main/java/com/chutneytesting/jira/infra/JiraTargetConfigurationDto.java
  jira/src/test/java/com/chutneytesting/jira/api/JiraModuleControllerTest.java
  jira/src/test/java/com/chutneytesting/jira/api/JiraXrayEmbeddedApiTest.java
  jira/src/test/java/com/chutneytesting/jira/infra/HttpJiraXrayImplTest.java
  jira/src/test/resources/jira/jira_config.json
  server/src/test/java/blackbox/SecuredControllerSpringBootIntegrationTest.java
  ui/src/app/core/model/jira-plugin-configuration.model.ts
  ui/src/app/modules/plugins/components/jira/jira.component.html
  ui/src/app/modules/plugins/components/jira/jira.component.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement, java

#1195 Clean DB migration test and target security migration
  environment/src/main/java/com/chutneytesting/environment/EnvironmentConfiguration.java
  environment/src/main/java/com/chutneytesting/environment/infra/MigrateTargetSecurityExecutor.java
  environment/src/test/java/com/chutneytesting/environment/EnvironmentConfigurationTest.java
  environment/src/test/java/com/chutneytesting/environment/EnvironmentSpringConfigurationTest.java
  environment/src/test/java/com/chutneytesting/environment/infra/MigrateTargetSecurityExecutorTest.java
  server/src/test/java/changelog/LiquibaseChangelogTest.java
  server/src/test/java/util/infra/EnableH2FileTestInfra.java
  server/src/test/java/util/infra/TestInfraConfiguration.java
Labels: java, technical

#1200 feat: assert that no kafka message consumed
  action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaBasicConsumeAction.java
  action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionTest.java
Labels: enhancement

#1201 If strategy : Set correctly all substeps status
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/IfStrategy.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/IfStrategyTest.java
Labels: bug

#1194 Clean components relatives
  .idea/runConfigurations/server_integration_tests.xml
  pom.xml
  server-core/src/main/java/com/chutneytesting/server/core/domain/execution/processor/TestCasePreProcessor.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/TestCase.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/Campaign.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/CampaignBuilder.java
  server-core/src/test/java/com/chutneytesting/server/core/domain/execution/processor/TestCasePreProcessorTest.java
  server/src/main/java/com/chutneytesting/campaign/api/dto/CampaignDto.java
  server/src/main/java/com/chutneytesting/campaign/api/dto/CampaignMapper.java
  server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignEntity.java
  server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignParameterEntity.java
  server/src/main/java/com/chutneytesting/execution/api/IdeaRequest.java
  server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionUiController.java
  server/src/main/java/com/chutneytesting/execution/domain/GwtDataSetPreProcessor.java
  server/src/main/java/com/chutneytesting/execution/domain/RawDataSetPreProcessor.java
  server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  server/src/main/java/com/chutneytesting/scenario/api/GwtTestCaseController.java
  server/src/main/java/com/chutneytesting/scenario/api/raw/dto/GwtTestCaseDto.java
  server/src/main/java/com/chutneytesting/scenario/api/raw/dto/RawTestCaseDto.java
  server/src/main/java/com/chutneytesting/scenario/api/raw/mapper/GwtTestCaseMapper.java
  server/src/main/java/com/chutneytesting/scenario/api/raw/mapper/RawTestCaseMapper.java
  server/src/main/java/com/chutneytesting/scenario/domain/gwt/GwtTestCase.java
  server/src/main/java/com/chutneytesting/scenario/domain/raw/RawTestCase.java
  server/src/main/java/com/chutneytesting/scenario/infra/jpa/ScenarioEntity.java
  server/src/main/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepository.java
  server/src/main/java/com/chutneytesting/scenario/infra/raw/ScenarioJpaRepository.java
  server/src/main/resources/changelog/db.changelog-master.xml
  server/src/test/java/changelog/LiquibaseChangelogTest.java
  server/src/test/java/com/chutneytesting/campaign/api/CampaignControllerTest.java
  server/src/test/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepositoryTest.java
  server/src/test/java/com/chutneytesting/campaign/infra/FakeCampaignRepository.java
  server/src/test/java/com/chutneytesting/design/domain/editionlock/TestCaseEditionsServiceTest.java
  server/src/test/java/com/chutneytesting/execution/domain/DataSetPreProcessorTest.java
  server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
  server/src/test/java/com/chutneytesting/scenario/api/GwtTestCaseControllerTest.java
  server/src/test/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepositoryTest.java
  server/src/test/java/util/infra/AbstractLocalDatabaseTest.java
  server/src/test/java/util/infra/TestInfraConfiguration.java
  server/src/test/resources/blackbox/engine/parameters.feature
  server/src/test/resources/raw_scenarios/testcase_for_global_vars.v2.1.json
  ui/src/app/core/model/campaign/campaign.model.ts
  ui/src/app/core/model/component-task.model.ts
  ui/src/app/core/model/dataset.model.ts
  ui/src/app/core/model/index.ts
  ui/src/app/core/model/scenario/example-parameters.model.ts
  ui/src/app/core/model/scenario/gwt-test-case.model.ts
  ui/src/app/core/model/scenario/index.ts
  ui/src/app/core/model/scenario/test-case.model.ts
  ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.ts
  ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.ts
  ui/src/app/modules/scenarios/services/scenario-execution.service.ts
Labels: technical

#1204 Prepare next development 2.5.1-SNAPSHOT
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1206 Release 2.5.1
  CHANGELOG.md
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1207 Prepare next development 2.5.2-SNAPSHOT
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1209 Fix running report header date
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.html
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
  ui/src/app/modules/scenarios/services/scenario-execution.service.ts
Labels: bug, UI

#1211 Defensive copy in step state when requesting messages
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/step/StepState.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/step/StepStateTest.java
Labels: bug, java
