Repository chutney-testing/chutney, pull requests merged in 2023-09, with the labels that each got.

#1070 fix(action-impl): kafka action - filter by content type
  action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaBasicConsumeAction.java
  action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionTest.java
Labels: bug

#1133 chore: Release 2.2.1
  CHANGELOG.md
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  component/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1134 chore: Prepare next development 2.3.0-SNAPSHOT
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  component/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1130 feature(scenario execution): update report to set the status to STOPP…
  server/src/main/java/com/chutneytesting/campaign/infra/CampaignExecutionDBRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignExecution.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionJpaRepository.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/ScenarioExecutionReportJpaRepository.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionEntity.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionReportEntity.java
  server/src/main/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepository.java
  server/src/test/java/changelog/LiquibaseChangelogTest.java
  server/src/test/java/com/chutneytesting/admin/infra/DatabaseAdminServiceImplTest.java
  server/src/test/java/com/chutneytesting/campaign/infra/CampaignExecutionRepositoryTest.java
  server/src/test/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepositoryTest.java
  server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  server/src/test/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepositoryTest.java
  server/src/test/java/util/infra/AbstractLocalDatabaseTest.java
Labels: technical

#1129 Feature/trust store target implementation
  action-impl/pom.xml
  action-impl/src/main/java/com/chutneytesting/action/kafka/ChutneyKafkaProducerFactory.java
  action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaConsumerFactoryFactory.java
  action-impl/src/main/java/com/chutneytesting/action/mongo/DefaultMongoDatabaseFactory.java
  action-impl/src/test/java/com/chutneytesting/action/http/HttpActionTest.java
  action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionTest.java
  action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicPublishActionTest.java
  action-impl/src/test/java/com/chutneytesting/action/mongo/DefaultMongoDatabaseFactoryTest.java
  action-impl/src/test/java/com/chutneytesting/action/ssh/SftpActionTest.java
  action-impl/src/test/resources/security/cacerts
  action-impl/src/test/resources/security/mongod.conf
  action-impl/src/test/resources/security/server.pem
Labels: technical

#1139 chore: Release 2.2.2
  CHANGELOG.md
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  component/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release
