Repository chutney-testing/chutney, pull requests merged in 2023-10, with the labels that each got.

#1142 feat(campaign): Endpoint to get the last campaign execution for a given campaign
  pom.xml
  server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/CampaignExecutionReport.java
  server/pom.xml
  server/src/main/java/com/chutneytesting/campaign/domain/CampaignExecutionRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/CampaignExecutionDBRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/CampaignExecutionJpaRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/CampaignJpaRepository.java
  server/src/main/java/com/chutneytesting/execution/api/CampaignExecutionApiMapper.java
  server/src/main/java/com/chutneytesting/execution/api/CampaignExecutionReportSummaryDto.java
  server/src/main/java/com/chutneytesting/execution/api/CampaignExecutionUiController.java
  server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionNotFoundException.java
  server/src/test/java/com/chutneytesting/campaign/infra/CampaignExecutionRepositoryTest.java
  server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
Labels: enhancement, java

#1155 Chore/webconfig
  pom.xml
  server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/execution/report/StepExecutionReportCore.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/tools/Default.java
  server/src/main/java/com/chutneytesting/ServerConfiguration.java
  server/src/main/java/com/chutneytesting/WebConfiguration.java
  server/src/main/java/com/chutneytesting/agent/infra/storage/JsonFileAgentNetworkDao.java
  server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionHistoryController.java
  server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionReportCoreMapper.java
  server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionReportDto.java
  server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionReportMapper.java
  server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionUiController.java
  server/src/main/java/com/chutneytesting/execution/api/StepExecutionReportCoreDto.java
  server/src/main/java/com/chutneytesting/execution/api/report/surefire/SurefireScenarioExecutionReportBuilder.java
  server/src/main/java/com/chutneytesting/execution/infra/execution/DefaultExecutionRequestMapper.java
  server/src/test/java/changelog/LiquibaseChangelogTest.java
  server/src/test/java/com/chutneytesting/ServerConfigurationTest.java
  server/src/test/java/com/chutneytesting/admin/infra/DatabaseAdminServiceImplTest.java
  server/src/test/java/com/chutneytesting/agent/api/NodeNetworkControllerTest.java
  server/src/test/java/com/chutneytesting/agent/infra/HttpAgentClientTest.java
  server/src/test/java/com/chutneytesting/campaign/api/CampaignControllerTest.java
  server/src/test/java/com/chutneytesting/campaign/infra/CampaignExecutionRepositoryTest.java
  server/src/test/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepositoryTest.java
  server/src/test/java/com/chutneytesting/design/api/editionlock/TestCaseEditionControllerTest.java
  server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  server/src/test/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepositoryTest.java
  server/src/test/java/util/infra/TestInfraConfiguration.java
Labels: java, technical

#1156 fix(server): scenarios with same name bug on surefire campaign report
  server/src/main/java/com/chutneytesting/execution/api/report/surefire/SurefireScenarioExecutionReportBuilder.java
  server/src/test/java/com/chutneytesting/execution/api/report/surefire/SurefireCampaignExecutionReportBuilderTest.java
  server/src/test/java/com/chutneytesting/execution/api/report/surefire/SurefireScenarioExecutionReportBuilderTest.java
Labels: bug

#1158 feat(ui): preview imported execution
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.html
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
  ui/src/app/modules/scenarios/components/execution/preview/report-preview.component.html
  ui/src/app/modules/scenarios/components/execution/preview/report-preview.component.scss
  ui/src/app/modules/scenarios/components/execution/preview/report-preview.component.ts
  ui/src/app/modules/scenarios/scenario.module.ts
  ui/src/app/modules/scenarios/scenario.routes.ts
  ui/src/app/shared/components/layout/left-menu/chutney-left-menu.items.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement

#1157 feat(action): Add headless for selenium action
  action-impl/pom.xml
  action-impl/src/main/java/com/chutneytesting/action/selenium/SeleniumDriverInitAction.java
  action-impl/src/main/java/com/chutneytesting/action/selenium/SeleniumRemoteDriverInitAction.java
  action-impl/src/main/java/com/chutneytesting/action/selenium/driver/AbstractSeleniumDriverInitAction.java
  action-impl/src/main/java/com/chutneytesting/action/selenium/driver/SeleniumChromeDriverInitAction.java
  action-impl/src/main/java/com/chutneytesting/action/selenium/driver/SeleniumFirefoxDriverInitAction.java
  action-impl/src/main/java/com/chutneytesting/action/selenium/driver/SeleniumGenericDriverInitAction.java
  action-impl/src/main/resources/META-INF/extension/chutney.actions
  action-impl/src/test/java/com/chutneytesting/action/jms/IntTest.java
  action-impl/src/test/java/com/chutneytesting/action/selenium/SeleniumDriverInitActionTest.java
  action-impl/src/test/java/com/chutneytesting/action/selenium/SeleniumRemoteDriverInitActionTest.java
  action-impl/src/test/java/com/chutneytesting/action/selenium/SeleniumTest.java
  action-impl/src/test/java/com/chutneytesting/action/selenium/driver/SeleniumDriverInitActionTest.java
Labels: enhancement

#1159 if strategy
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/evaluation/StepDataEvaluator.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/DataSetIterationsStrategy.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/IfStrategy.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/StepIterationStrategy.java
  engine/src/main/resources/META-INF/extension/chutney.strategies
  engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/DataSetIterationsStrategyTest.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/IfStrategyTest.java
  engine/src/test/resources/META-INF/extension/chutney.strategies
Labels: enhancement

#1160 chore: Release 2.3.0
  CHANGELOG.md
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1161 Prepare next development 2.3.1-SNAPSHOT
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release
