Repository chutney-testing/chutney, pull requests merged in 2024-04, with the labels that each got.

#45 chore(server): Audit api call (not GET)
  chutney/server/src/main/java/com/chutneytesting/WebConfiguration.java
  chutney/server/src/main/java/com/chutneytesting/security/AuditHandler.java
  chutney/server/src/test/java/com/chutneytesting/security/AuditHandlerTest.java
Labels: technical

#48 feat(server): iterate over dataset constants when datatable is empty
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/DefaultExecutionEngine.java
  chutney/engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/DefaultExecutionEngineTest.java
  chutney/engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/ForEachStrategyTest.java
  chutney/engine/src/test/resources/scenarios_examples/forEachStrategy/simple_step_iterations_over_constants.json
  docs/.gitignore
  docs/Dockerfile
  docs/README.md
  docs/docs/documentation/dataset.md
  docs/docs/getting_started/write.md
  docs/docs/img/dataset/declare-constant-ui.png
  docs/docs/img/dataset/declare-datatable-ui.png
  docs/docs/img/dataset/link-dataset-to-campaign-ui.png
  docs/docs/img/dataset/link-dataset-to-scenario-ui.png
  docs/mkdocs.yml
  kotlin-dsl/dsl/src/test/kotlin/com/chutneytesting/kotlin/execution/ExecutionServiceTest.kt
Labels: documentation, enhancement

#63 feat/campaign-parallel-exec
  chutney/server/src/main/java/com/chutneytesting/campaign/domain/CampaignExecutionRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/CampaignExecutionDBRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignExecutionEntity.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignAlreadyRunningException.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  chutney/server/src/test/java/com/chutneytesting/campaign/infra/FakeCampaignRepository.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
  chutney/ui/src/app/modules/campaign/components/execution/history/campaign-executions-history.component.ts
Labels: enhancement

#64 Free system port function
  chutney/action-impl/src/main/java/com/chutneytesting/action/function/NetworkFunctions.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/function/NetworkFunctionsTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/jakarta/ActiveMQTestSupport.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/jakarta/JakartaSenderActionWithActiveMqIntegrationTest.java
  chutney/engine/src/test/java/com/chutneytesting/engine/domain/report/ReporterTest.java
  chutney/engine/src/test/resources/junit-platform.properties
  chutney/tools/src/main/java/com/chutneytesting/tools/SocketUtils.java
  docs/docs/documentation/functions/network.md
  kotlin-dsl/dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyFunctions.kt
  kotlin-dsl/dsl/src/test/kotlin/com/chutneytesting/kotlin/dsl/ChutneyFunctionsTest.kt
Labels: enhancement

#65 Delete dataset version property
  chutney/action-impl/src/test/resources/logback-test.xml
  chutney/pom.xml
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/dataset/DataSet.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/dataset/DataSetHistoryRepository.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/history/ExecutionHistory.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/CampaignExecution.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/CampaignExecutionReportBuilder.java
  chutney/server-core/src/test/java/com/chutneytesting/server/core/domain/dataset/DatasetTest.java
  chutney/server/pom.xml
  chutney/server/src/main/java/com/chutneytesting/ServerConfiguration.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignExecutionEntity.java
  chutney/server/src/main/java/com/chutneytesting/dataset/api/DataSetDto.java
  chutney/server/src/main/java/com/chutneytesting/dataset/api/DataSetMapper.java
  chutney/server/src/main/java/com/chutneytesting/dataset/api/KeyValue.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionEntity.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionReportEntity.java
  chutney/server/src/main/resources/changelog/db.changelog-master.xml
  chutney/server/src/test/java/changelog/LiquibaseChangelogTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/api/CampaignControllerTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/domain/CampaignExecutionTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/domain/CampaignServiceTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/infra/CampaignExecutionDBRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/dataset/api/DataSetControllerTest.java
  chutney/server/src/test/java/com/chutneytesting/dataset/api/DataSetMapperTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/api/report/surefire/SurefireCampaignExecutionReportBuilderTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/PurgeServiceTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  chutney/server/src/test/java/util/infra/AbstractLocalDatabaseTest.java
  chutney/ui/src/app/core/model/dataset.model.ts
  chutney/ui/src/app/core/services/dataset.service.ts
  chutney/ui/src/app/modules/dataset/components/dataset-edition/dataset-edition.component.ts
Labels: technical

#62 Purge - Keep executions newer than 24 hours
  chutney/pom.xml
  chutney/server/src/main/java/com/chutneytesting/SchedulingConfiguration.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/purge/PurgeExecutionsFilters.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/purge/PurgeServiceImpl.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/purge/PurgeExecutionsFiltersTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/purge/PurgeServiceTest.java
Labels: enhancement

#68 Docs : Time rules spEL functions
  chutney/action-impl/src/main/java/com/chutneytesting/action/function/DateTimeFunctions.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/function/DateTimeFunctionsTest.java
  docs/docs/documentation/actions/micrometer.md
  docs/docs/documentation/actions/ssh.md
  docs/docs/documentation/functions/classpath.md
  docs/docs/documentation/functions/datetime.md
  docs/docs/documentation/functions/generate.md
  docs/docs/documentation/functions/nullable.md
  kotlin-dsl/dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyFunctions.kt
  kotlin-dsl/dsl/src/test/kotlin/com/chutneytesting/kotlin/dsl/ChutneyFunctionsTest.kt
Labels: enhancement
