Repository chutney-testing/chutney, pull requests merged in 2024-06, with the labels that each got.

#84 Feat/select dataset for each scenario in campaign
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.html
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.scss
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.ts
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
Labels: enhancement

#103 Set dynamic ports for servers' start test
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
Labels: technical

#88 feat(): show dataset content in execution report
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/DefaultExecutionEngine.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngine.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/report/ScenarioExecutionReport.java
  chutney/server-core/src/test/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsyncTest.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/execution/DefaultExecutionRequestMapperTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  chutney/ui/src/app/core/model/scenario/scenario-execution-report.model.ts
  chutney/ui/src/app/core/services/campaign-report.service.ts
  chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.scss
  chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
  chutney/ui/src/app/modules/scenarios/services/scenario-execution.service.ts
  chutney/ui/src/assets/i18n/fr.json
Labels: enhancement

#91 fix(): fix old table deletion
  chutney/server/src/main/resources/changelog/db.changelog-master.xml
Labels: technical

#105 fix(jira): Allow no proxy configuration for JIRA configuration
  chutney/jira/src/main/java/com/chutneytesting/jira/infra/HttpJiraXrayImpl.java
  chutney/jira/src/test/java/com/chutneytesting/jira/infra/HttpJiraXrayImplTest.java
Labels: bug

#92 fix(): Change scenarios default dataset id from "null" to null
  chutney/server/src/main/resources/changelog/db.changelog-master.xml
Labels: technical

#107 fix(): cursor pointer on report step title hover
  chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.html
Labels: bug

#108 fix(): fix scenarios list scroll
  chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.html
Labels: bug

#110 Order environment by name on target edition
  chutney/ui/src/app/modules/target/details/target.component.ts
Labels: enhancement

#111 Release 2.9.0
  CHANGELOG.md
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/chutney-junit/api/pom.xml
  chutney/chutney-junit/engine/pom.xml
  chutney/chutney-junit/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/glacio-adapter/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  idea-plugin/gradle.properties
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/AddScenarioToLocalServer.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/util/StringUtils.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/vcs/ChutneyCheckinHandler.kt
  kotlin-dsl/gradle.properties
Labels: release

#112 Prepare next development 2.9.1-SNAPSHOT
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/chutney-junit/api/pom.xml
  chutney/chutney-junit/engine/pom.xml
  chutney/chutney-junit/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/glacio-adapter/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  idea-plugin/gradle.properties
  kotlin-dsl/gradle.properties
Labels: release

#113 Scenarios list refresh must be unsubscribed
  chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.ts
Labels: bug

#115 fix(ui): fix campaign edition filters width
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.html
Labels: bug

#87 Update campaigns when renaming environment
  chutney/environment/src/main/java/com/chutneytesting/environment/EnvironmentConfiguration.java
  chutney/environment/src/main/java/com/chutneytesting/environment/EnvironmentSpringConfiguration.java
  chutney/environment/src/main/java/com/chutneytesting/environment/api/EnvironmentRestExceptionHandler.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/EnvironmentService.java
  chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/SingleEnvironmentException.java
  chutney/environment/src/test/java/com/chutneytesting/environment/api/environment/HttpEnvironmentApiTest.java
  chutney/environment/src/test/java/com/chutneytesting/environment/api/target/TargetControllerTest.java
  chutney/environment/src/test/java/com/chutneytesting/environment/api/variable/VariableControllerTest.java
  chutney/environment/src/test/java/com/chutneytesting/environment/domain/EnvironmentServiceTest.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/environment/UpdateEnvironmentHandler.java
  chutney/server/src/main/java/com/chutneytesting/RestExceptionHandler.java
  chutney/server/src/main/java/com/chutneytesting/ServerConfiguration.java
  chutney/server/src/main/java/com/chutneytesting/campaign/api/CampaignController.java
  chutney/server/src/main/java/com/chutneytesting/campaign/domain/CampaignEnvironmentUpdateHandler.java
  chutney/server/src/main/java/com/chutneytesting/campaign/domain/CampaignRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/CampaignJpaRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepository.java
  chutney/server/src/test/java/blackbox/SecuredControllerSpringBootIntegrationTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/domain/CampaignEnvironmentUpdateHandlerTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/infra/FakeCampaignRepository.java
  chutney/ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.html
  chutney/ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.scss
  chutney/ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.ts
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.html
  chutney/ui/src/app/modules/environment/list/environments.component.ts
  chutney/ui/src/app/shared/components/environment-combo/environment-combo.component.html
  chutney/ui/src/app/shared/components/environment-combo/environment-combo.component.ts
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
Labels: bug

#116 Fix campaign execution status
  .idea/runConfigurations/server_unit_tests.xml
  chutney/packaging/local-dev/src/main/resources/application-db-pg.yml
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/CampaignExecution.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/CampaignExecutionReportBuilder.java
  chutney/server-core/src/test/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsyncTest.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/CampaignExecutionDBRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignExecutionEntity.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  chutney/server/src/test/java/com/chutneytesting/campaign/api/CampaignControllerTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/domain/CampaignExecutionTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/domain/CampaignServiceTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/infra/CampaignExecutionDBRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/infra/jpa/CampaignExecutionEntityTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/api/report/surefire/SurefireCampaignExecutionReportBuilderTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/purge/PurgeServiceTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  chutney/ui/src/app/modules/campaign/components/execution/history/list/campaign-executions.component.html
Labels: bug

#117 feat(ui) : Use the id instead of the name for scenario dataset in cam…
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/dataset/DataSetNotFoundException.java
  chutney/server/src/main/java/com/chutneytesting/RestExceptionHandler.java
  chutney/server/src/main/java/com/chutneytesting/campaign/api/CampaignController.java
  chutney/server/src/main/java/com/chutneytesting/dataset/infra/FileDatasetRepository.java
  chutney/server/src/test/java/com/chutneytesting/campaign/api/CampaignControllerTest.java
  chutney/server/src/test/java/com/chutneytesting/dataset/infra/FileDatasetRepositoryTest.java
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.ts
Labels: bug

#119 Campaign edition - JIRA filter not present
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.html
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.scss
Labels: bug

#120 fix(ui) : break long word in admin bdd search, fix overflow ng-multi…
  chutney/ui/src/app/modules/campaign/components/create-campaign/campaign-edition.component.scss
  chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.html
  chutney/ui/src/app/modules/database-admin/components/resultReportList/database-admin-report-list.component.html
  chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.html
  chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.html
  chutney/ui/src/assets/style/global/_select.scss
Labels: bug
