Repository chutney-testing/chutney, pull requests merged in 2024-01, with the labels that each got.

#1225 Add environment at first save of campaignExecutionEngine
  server/src/main/java/com/chutneytesting/ServerConfiguration.java
  server/src/main/java/com/chutneytesting/campaign/api/CampaignController.java
  server/src/main/java/com/chutneytesting/campaign/domain/CampaignExecutionRepository.java
  server/src/main/java/com/chutneytesting/campaign/domain/CampaignRepository.java
  server/src/main/java/com/chutneytesting/campaign/domain/CampaignService.java
  server/src/main/java/com/chutneytesting/campaign/infra/CampaignExecutionDBRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignExecutionEntity.java
  server/src/main/java/com/chutneytesting/execution/domain/PurgeServiceImpl.java
  server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  server/src/test/java/com/chutneytesting/campaign/api/CampaignControllerTest.java
  server/src/test/java/com/chutneytesting/campaign/domain/CampaignServiceTest.java
  server/src/test/java/com/chutneytesting/campaign/infra/CampaignExecutionDBRepositoryTest.java
  server/src/test/java/com/chutneytesting/campaign/infra/FakeCampaignRepository.java
  server/src/test/java/com/chutneytesting/execution/domain/PurgeServiceTest.java
  server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
  server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
Labels: bug

#1227 Purge - Handle runtime exception. Add Spring configuration on parameters.
  packaging/local-api-unsecure/src/main/resources/application.yml
  packaging/local-dev/src/main/resources/application.yml
  server/src/main/java/com/chutneytesting/ServerConfigurationValues.java
  server/src/main/java/com/chutneytesting/execution/api/schedule/SchedulePurge.java
  server/src/test/java/com/chutneytesting/execution/api/schedule/SchedulePurgeTest.java
Labels: bug, java

#1226 Fix/double for strategy
  engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/step/Step.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/ForEachStrategy.java
  engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/StepExecutionStrategy.java
  engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/ForEachStrategyTest.java
  engine/src/test/resources/scenarios_examples/forEachStrategy/error_without_dataset_iterations.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/final_step_iteration_strategy_with_variable_in_name_from_context_put_and_datset.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/iteration_strategy_step_with_name_resolver_from_context_put.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/iteration_strategy_using_idx_in_sub_sub_step.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/iteration_strategy_using_value_in_sub_sub_sub_step.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/iteration_strategy_with_variable_in_name_from_context_put_and_datset.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/simple_step_iterations.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/simple_step_iterations_fail_at_end.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/step_double_nested_iterations_with_different_dataset.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/step_iteration_evaluated_dataset.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/step_iteration_preserve_input_types.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/step_iterations_using_data_from_context.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/step_iterations_with_parent_and_substeps.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/step_nested_iterations_with_different_dataset.json
  engine/src/test/resources/scenarios_examples/forEachStrategy/step_nested_iterations_with_overridden_dataset.json
Labels: bug

#1229 Release 2.6.0
  CHANGELOG.md
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1230 chore(): Prepare next development 2.6.1-SNAPSHOT
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1232 chore: Release 2.6.1
  CHANGELOG.md
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1233 chore: Prepare next development 2.6.2-SNAPSHOT
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release
