Repository chutney-testing/chutney, pull requests merged in 2024-09, with the labels that each got.

#181 Add JUnit 5 test dependencies to example project
  example/pom.xml
Labels: technical

#169 feat(server+ui): allow delete scenario executions
  chutney/server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionHistoryController.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.ts
  chutney/ui/src/app/modules/scenarios/services/scenario-execution.service.ts
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
Labels: enhancement

#182 fix(action-impl): fix selenium driver init actions
  chutney/action-impl/src/main/java/com/chutneytesting/action/selenium/driver/AbstractSeleniumDriverInitAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/selenium/driver/SeleniumFirefoxDriverInitAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/selenium/driver/SeleniumGenericDriverInitAction.java
Labels: bug

#183 Support idea 242
  .gitattributes
  idea-plugin/.gitignore
  idea-plugin/build.gradle.kts
  idea-plugin/gradle.properties
  idea-plugin/gradle/wrapper/gradle-wrapper.jar
  idea-plugin/gradle/wrapper/gradle-wrapper.properties
  idea-plugin/gradlew
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/ChutneyJsonSchemaV1FileProvider.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/ChutneyJsonSchemaV2FileProvider.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/ChutneySchemaProviderFactory.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/ChutneyUtil.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/AddRemoveScenarioInCampaignAction.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/AddRemoveScenarionInCampaignsActionGroup.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/AddScenarioToLocalServer.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/AddScenarioToRemoteServer.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/CopyScenarioAsKotlinDslAction.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/GetCampaignFromRemoteServer.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/GetScenarioFromRemoteServer.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/OpenChutneyConfigFileAction.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/PasteHJsonFromClipBoardAction.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/UpdateRemoteScenarioFromLocal.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/actions/UpdateScenarioToV2Action.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/folding/StepFoldingBuilder.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/gutter/ChutneyKotlinSynchroniseWithRemoteLineMarkerProvider.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/runner/ChutneyJsonLineMarkerProvider.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/runner/ChutneyRunConfigurationProducer.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/runner/JsonTestReportsParser.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/runner/JsonTestScenariosParser.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/runner/settings/ChutneyRunSettingsSerializationUtils.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/server/ui/ChutneyServerRestartAction.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/server/ui/ChutneyServerStatusView.kt
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/server/ui/ChutneyServerStopAction.kt
  idea-plugin/src/main/resources/META-INF/plugin.xml
  idea-plugin/src/main/resources/chutney-v1.schema.json
  idea-plugin/src/main/resources/chutney-v2.schema.json
Labels: technical

#167 Supervise demo instance with prometheus and grafana
  example/.docker/README.md
  example/.docker/demo/conf/chutney-demo.db
  example/.docker/demo/conf/chutney-demo.db-shm
  example/.docker/demo/conf/chutney-demo.db-wal
  example/.docker/dev-docker-compose-demo.yml
  example/.docker/supervision/grafana/dashboards/chutney/executions.json
  example/.docker/supervision/grafana/dashboards/chutney/jvm.json
  example/.docker/supervision/grafana/dashboards/prometheus/prometheus.json
  example/.docker/supervision/grafana/dashboards/providers.yml
  example/.docker/supervision/grafana/datasources/datasources.yml
  example/.docker/supervision/prometheus/prometheus.yml
Labels: enhancement

#184 Fix/dataset jira
  chutney/ui/src/app/modules/scenarios/components/scenario-jira-links-modal/scenario-jira-links-modal.component.ts
Labels: bug

#186 chore(): dsl as maven project. add parent maven project
  .github/actions/build-chutney/action.yml
  .github/actions/build-dsl/action.yml
  .github/actions/build-example/action.yml
  .github/workflows/build-all-template.yml
  .github/workflows/codeql-analysis-template.yml
  .github/workflows/codeql-analysis.yml
  .gitignore
  .idea/copyright/apache2.xml
  .mvn/wrapper/maven-wrapper.properties
  CONTRIBUTING.md
  acceptance-tests/.gitignore
  acceptance-tests/pom.xml
  chutney/.gitignore
  chutney/packaging/pom.xml
  chutney/pom.xml
  docs/docs/getting_started/run.md
  example/.gitignore
  example/mvnw
  example/mvnw.cmd
  example/pom.xml
  example/src/test/kotlin/com/chutneytesting/example/scenario/RunHelloTests.kt
  kotlin-dsl/.gitignore
  kotlin-dsl/build.gradle.kts
  kotlin-dsl/gradle.properties
  kotlin-dsl/gradle/wrapper/gradle-wrapper.jar
  kotlin-dsl/gradle/wrapper/gradle-wrapper.properties
  kotlin-dsl/gradlew
  kotlin-dsl/gradlew.bat
  kotlin-dsl/pom.xml
  kotlin-dsl/settings.gradle.kts
  kotlin-dsl/src/main/java/com/chutneytesting/kotlin/junit/api/ChutneyTest.java
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/annotations/ChutneyTest.kt
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/junit/engine/DiscoverySelectorResolver.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/HttpTestBase.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/junit/engine/ChutneyTest.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/junit/engine/ChutneyTestEngineTest.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/junit/engine/SameMethodNameClassTest.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/synchronize/server/ChutneyServerServiceImplTest.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/util/ChutneyServerInfoTest.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/util/HttpClientTest.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/util/HttpsClientTest.kt
  kotlin-dsl/src/test/kotlin/util/ChutneyServerInfoClearProperties.kt
  mvnw
  mvnw.cmd
  pom.xml
Labels: technical

#185 Request scenarios' executions to stop when stopping campaign execution
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/ScenarioExecutionCampaign.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/tools/DatasetUtils.java
  chutney/server-core/src/test/java/com/chutneytesting/server/core/domain/tools/DatasetUtilsTest.java
  chutney/server/src/main/java/com/chutneytesting/ServerConfiguration.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
Labels: enhancement
