Repository chutney-testing/chutney, pull requests merged in 2024-11, with the labels that each got.

#204 feat(server, ui): Show dataset usage in dataset page
  chutney/server-core/pom.xml
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/dataset/DataSet.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/AggregatedRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/domain/CampaignRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/CampaignJpaRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/CampaignScenarioJpaRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepository.java
  chutney/server/src/main/java/com/chutneytesting/dataset/api/DataSetController.java
  chutney/server/src/main/java/com/chutneytesting/dataset/api/DataSetDto.java
  chutney/server/src/main/java/com/chutneytesting/dataset/api/DataSetMapper.java
  chutney/server/src/main/java/com/chutneytesting/dataset/domain/DatasetService.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/TestCaseRepositoryAggregator.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepository.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/ScenarioJpaRepository.java
  chutney/server/src/test/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/infra/FakeCampaignRepository.java
  chutney/server/src/test/java/com/chutneytesting/dataset/api/DataSetMapperTest.java
  chutney/server/src/test/java/com/chutneytesting/dataset/domain/DatasetServiceTest.java
  chutney/ui/src/app/core/model/dataset.model.ts
  chutney/ui/src/app/core/services/dataset.service.ts
  chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.html
  chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.scss
  chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.ts
Labels: enhancement

#218 fix(jira): Check test plan only when the campaign is linked with jira issue
  chutney/jira/src/main/java/com/chutneytesting/jira/infra/HttpJiraXrayImpl.java
  chutney/jira/src/test/java/com/chutneytesting/jira/infra/HttpJiraXrayImplTest.java
Labels: bug

#208 Feat/zip
  chutney/packaging/local-dev/src/main/resources/application.yml
  chutney/pom.xml
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/history/ExecutionHistoryRepository.java
  chutney/server/pom.xml
  chutney/server/src/main/java/com/chutneytesting/ServerConfiguration.java
  chutney/server/src/main/java/com/chutneytesting/admin/api/DatabaseManagementController.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/aop/ScenarioExecutionReportIndexingAspect.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/migration/ZipReportMigration.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionJpaRepository.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ReportConverter.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionReportEntity.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/IndexConfig.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/IndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/OnDiskIndexConfig.java
  chutney/server/src/main/java/com/chutneytesting/index/infra/ScenarioExecutionReportIndexRepository.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepository.java
  chutney/server/src/main/resources/changelog/db.changelog-master.xml
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/index/infra/IndexRepositoryTest.java
  chutney/server/src/test/java/util/infra/AbstractLocalDatabaseTest.java
  chutney/server/src/test/java/util/infra/TestInfraConfiguration.java
Labels: enhancement

#219 SSH action proxy jump
  .github/workflows/build-all-template.yml
  .github/workflows/release-to-github.yml
  .github/workflows/release-to-ossrh.yml
  .gitignore
  acceptance-tests/pom.xml
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/AcceptanceTests.kt
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/common/ScenarioSteps.kt
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/common/SshTests.kt
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/tests/AgentAcceptanceTest.kt
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/tests/CampaignAcceptanceTest.kt
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/tests/ScenarioAcceptanceTest.kt
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/tests/actions/JakartaTaskAcceptanceTest.kt
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/tests/actions/SshTaskAcceptanceTest.kt
  acceptance-tests/src/test/resources/blackbox/env/ssh/client-intern-id_edcsa.key
  acceptance-tests/src/test/resources/blackbox/env/ssh/client-intern-id_edcsa.pub
  acceptance-tests/src/test/resources/blackbox/env/ssh/client-jump-id_ecdsa.key
  acceptance-tests/src/test/resources/blackbox/env/ssh/client-jump-id_ecdsa.pub
  acceptance-tests/src/test/resources/blackbox/env/ssh/ssh-env-compose.yml
  acceptance-tests/src/test/resources/logback-test.xml
  acceptance-tests/src/test/resources/security/server.jks
  chutney/.docker/docker-compose-custom-config.yml
  chutney/.docker/docker-compose-local-dev.yml
  chutney/.docker/server/Dockerfile
  chutney/action-impl/src/main/java/com/chutneytesting/action/ssh/Connection.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/ssh/SshClientAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/ssh/sshd/Command.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/ssh/sshj/SshJClient.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/amqp/AmqpBasicConsumeActionTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/ssh/SshClientActionTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/ssh/SshServerActionTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/ssh/fakes/FakeServerSsh.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/ssh/fakes/FakeTargetInfo.java
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  example/.docker/dev-docker-compose-demo.yml
  example/pom.xml
  example/src/test/kotlin/com/chutneytesting/example/selenium/SeleniumTest.kt
  kotlin-dsl/pom.xml
  kotlin-dsl/src/test/kotlin/blackbox/IntegrationTest.kt
  kotlin-dsl/src/test/kotlin/util/WSLUtil.kt
  kotlin-dsl/src/test/resources/blackbox/application-mem-auth.yml
  kotlin-dsl/src/test/resources/blackbox/roles.json
  pom.xml
Labels: enhancement

#220 feat(action-impl): sql action can read blob type
  .gitattributes
  chutney/action-impl/pom.xml
  chutney/action-impl/src/main/java/com/chutneytesting/action/sql/core/SqlClient.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/sql/SqlActionTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/sql/core/SqlClientTest.java
  chutney/action-impl/src/test/resources/db/common/create_users.sql
  chutney/action-impl/src/test/resources/db/h2/create_types.sql
  chutney/action-impl/src/test/resources/db/oracle/create_types.sql
  chutney/action-impl/src/test/resources/db/oracle/init.sh
  chutney/action-impl/src/test/resources/db/sql/create_db.sql
  chutney/action-impl/src/test/resources/db/sql/insert_allsqltypes.sql
  chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.ts
  chutney/ui/src/app/modules/database-admin/components/resultReportList/database-admin-report-list.component.scss
Labels: enhancement

#222 chore(): Release 3.0.0
  CHANGELOG.md
  acceptance-tests/pom.xml
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  example/pom.xml
  idea-plugin/gradle.properties
  kotlin-dsl/pom.xml
  pom.xml
Labels: release

#225 chore(): Release 3.0.0
  CHANGELOG.md
  acceptance-tests/pom.xml
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  example/pom.xml
  idea-plugin/gradle.properties
  kotlin-dsl/pom.xml
  pom.xml
Labels: release
