Repository chutney-testing/chutney, pull requests merged in 2024-10, with the labels that each got.

#187 fix(): add idea report missing attributes
  idea-plugin/src/main/kotlin/com/chutneytesting/idea/runner/JsonTestReportsParser.kt
Labels: bug

#202 fix(kotlin-dsl): fix selenium screen-shot action
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyActionExtensions.kt
Labels: bug

#190 feat(action): Can set the key in Kafka producer, can read the key in Kafka consumer
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaBasicConsumeAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaBasicPublishAction.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionIntegrationTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicPublishActionTest.java
  kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyActionExtensions.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/dsl/ChutneyScenarioDslTest.kt
  kotlin-dsl/src/test/resources/dsl/kafka-actions.chutney.json
Labels: enhancement

#189 Fix .gitignore
  .gitignore
  acceptance-tests/.gitignore
  example/.gitignore
  kotlin-dsl/.gitignore
Labels: technical

#203 feat: Add SpEL support to RetryWithTimeOutStrategy
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/evaluation/StepDataEvaluator.java
  chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/strategies/RetryWithTimeOutStrategy.java
  chutney/engine/src/test/java/com/chutneytesting/engine/domain/execution/engine/evaluation/StepDataEvaluatorTest.java
  chutney/engine/src/test/java/com/chutneytesting/engine/domain/execution/strategies/RetryWithTimeOutStrategyTest.java
Labels: enhancement

#206 Remove oracle and ibm example dependency
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
Labels: technical

#205 Fix build in a wsl+docker dev env
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/AcceptanceTests.kt
  acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/tests/actions/SshTaskAcceptanceTest.kt
  kotlin-dsl/src/test/kotlin/com/chutneytesting/kotlin/synchronize/ScenarioSynchronizeServiceTest.kt
  mvnw
  mvnw.cmd
  pom.xml
Labels: technical
