Repository chutney-testing/chutney, pull requests merged in 2024-05, with the labels that each got.

#66 Change README
  .github/actions/build-chutney/action.yml
  .github/workflows/build-all-template.yml
  .github/workflows/build-all.yml
  GETTING_STARTED.md
  README.md
Labels: documentation

#82 Use dynamic port for jms tests
  chutney/server/src/test/resources/blackbox/actions/jakarta.feature
  chutney/server/src/test/resources/blackbox/actions/jms.feature
  kotlin-dsl/example/src/test/kotlin/com/chutneytesting/example/jms/JmsScenarioTest.kt
Labels: technical

#83 Take into account documentation label in Changelog template
  .github/release.yml
Labels: technical

#49 fix(): Update scenario list every 3 seconds when running
  chutney/ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.html
  chutney/ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.ts
  chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.ts
  chutney/ui/src/app/shared/components/execution-badge/execution-badge.component.scss
Labels: bug

#85 feat() : set tag from campaign to scenario execution
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ExecutionRequest.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/CampaignExecution.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
  chutney/server/src/test/java/com/chutneytesting/campaign/domain/CampaignExecutionTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
Labels: enhancement

#89 Remove ng-scrollbar
  chutney/ui/package-lock.json
  chutney/ui/package.json
  chutney/ui/src/app/shared/components/layout/left-menu/chutney-left-menu.component.html
  chutney/ui/src/app/shared/shared.module.ts
Labels: bug

#90 fix() : update tag design in table for campaign executions
  chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.html
  chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.scss
Labels: enhancement
