Repository chutney-testing/chutney, pull requests merged in 2024-02, with the labels that each got.

#1213 fix(engine): follow execution error
  .docker/ui/nginx/nginx.conf
  ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
  ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.ts
  ui/src/app/modules/scenarios/services/scenario-execution.service.ts
Labels: bug

#1235 feat(server+ui): scheduling sequential campaigns
  server/src/main/java/com/chutneytesting/campaign/api/ScheduleCampaignController.java
  server/src/main/java/com/chutneytesting/campaign/api/dto/SchedulingCampaignDto.java
  server/src/main/java/com/chutneytesting/campaign/domain/PeriodicScheduledCampaign.java
  server/src/main/java/com/chutneytesting/campaign/infra/SchedulingCampaignDto.java
  server/src/main/java/com/chutneytesting/campaign/infra/SchedulingCampaignFileRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/SchedulingCampaignsDtoDeserializer.java
  server/src/main/java/com/chutneytesting/execution/domain/schedule/CampaignScheduler.java
  server/src/test/java/blackbox/SecuredControllerSpringBootIntegrationTest.java
  server/src/test/java/com/chutneytesting/campaign/infra/PeriodicScheduledCampaignFileRepositoryTest.java
  server/src/test/java/com/chutneytesting/execution/domain/schedule/CampaignSchedulerTest.java
  ui/src/app/core/model/campaign/campaign-scheduling.model.ts
  ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.html
  ui/src/app/modules/campaign/components/campaign-scheduling/campaign-scheduling.component.html
  ui/src/app/modules/campaign/components/campaign-scheduling/campaign-scheduling.component.scss
  ui/src/app/modules/campaign/components/campaign-scheduling/campaign-scheduling.component.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement

#1237 Allow https proxy for jira client api
  jira/src/main/java/com/chutneytesting/jira/domain/JiraTargetConfiguration.java
  jira/src/main/java/com/chutneytesting/jira/infra/HttpJiraXrayImpl.java
  jira/src/main/java/com/chutneytesting/jira/infra/atlassian/httpclient/apache/httpcomponents/ApacheAsyncHttpClient.java
  jira/src/main/java/com/chutneytesting/jira/infra/atlassian/httpclient/apache/httpcomponents/DefaultHttpClientFactory.java
  jira/src/main/java/com/chutneytesting/jira/infra/atlassian/httpclient/apache/httpcomponents/MavenUtils.java
  jira/src/main/java/com/chutneytesting/jira/infra/atlassian/httpclient/apache/httpcomponents/PromiseHttpAsyncClient.java
  jira/src/main/java/com/chutneytesting/jira/infra/atlassian/httpclient/apache/httpcomponents/SettableFuturePromiseHttpPromiseAsyncClient.java
  jira/src/main/java/com/chutneytesting/jira/infra/atlassian/httpclient/api/factory/HttpClientOptions.java
  jira/src/main/java/com/chutneytesting/jira/infra/atlassian/httpclient/api/factory/ProxyOptions.java
  jira/src/main/java/com/chutneytesting/jira/infra/atlassian/jira/rest/client/internal/async/AsynchronousHttpClientFactory.java
  jira/src/test/java/com/chutneytesting/jira/infra/HttpJiraXrayImplTest.java
Labels: bug

#1236 Feature/admin search report
  server-core/src/main/java/com/chutneytesting/server/core/domain/admin/DatabaseAdminService.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/execution/history/ExecutionHistory.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/execution/history/ExecutionHistoryRepository.java
  server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/campaign/CampaignExecution.java
  server-core/src/test/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsyncTest.java
  server/src/main/java/com/chutneytesting/admin/api/DatabaseManagementController.java
  server/src/main/java/com/chutneytesting/admin/infra/DatabaseAdminServiceImpl.java
  server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignExecutionEntity.java
  server/src/main/java/com/chutneytesting/execution/api/ExecutionSummaryDto.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionJpaRepository.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/ExecutionRowMapper.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/ExecutionSummaryRowMapper.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionEntity.java
  server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionReportEntity.java
  server/src/test/java/blackbox/SecuredControllerSpringBootIntegrationTest.java
  server/src/test/java/com/chutneytesting/admin/infra/DatabaseAdminServiceImplTest.java
  server/src/test/java/com/chutneytesting/campaign/domain/CampaignExecutionTest.java
  server/src/test/java/com/chutneytesting/campaign/domain/CampaignServiceTest.java
  server/src/test/java/com/chutneytesting/execution/api/report/surefire/SurefireCampaignExecutionReportBuilderTest.java
  server/src/test/java/com/chutneytesting/execution/api/report/surefire/SurefireScenarioExecutionReportBuilderTest.java
  server/src/test/java/com/chutneytesting/execution/domain/PurgeServiceTest.java
  server/src/test/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngineTest.java
  server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  ui/src/app/core/model/scenario/execution.model.ts
  ui/src/app/core/services/database-admin.service.ts
  ui/src/app/modules/campaign/components/execution/history/list/campaign-executions.component.html
  ui/src/app/modules/database-admin/components/database-admin.component.html
  ui/src/app/modules/database-admin/components/database-admin.component.scss
  ui/src/app/modules/database-admin/components/database-admin.component.ts
  ui/src/app/modules/database-admin/components/resultReportList/database-admin-report-list.component.html
  ui/src/app/modules/database-admin/components/resultReportList/database-admin-report-list.component.ts
  ui/src/app/modules/database-admin/database-admin.module.ts
  ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.html
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: enhancement

#1251 filter NOT_EXECUTED when findLastExecutionsByScenarioId
  server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionJpaRepository.java
  server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
Labels: bug

#1249 Delete campaign from schedule after deleting campaign
  server/src/main/java/com/chutneytesting/campaign/domain/PeriodicScheduledCampaignRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/SchedulingCampaignFileRepository.java
  server/src/test/java/com/chutneytesting/campaign/infra/PeriodicScheduledCampaignFileRepositoryTest.java
  ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.ts
Labels: bug

#1234 DB compact for SQLite
  server/src/main/java/com/chutneytesting/RestExceptionHandler.java
  server/src/main/java/com/chutneytesting/admin/api/DatabaseManagementController.java
  server/src/main/java/com/chutneytesting/admin/domain/DBVacuum.java
  server/src/main/java/com/chutneytesting/admin/infra/DefaultDBVacuum.java
  server/src/test/java/blackbox/SecuredControllerSpringBootIntegrationTest.java
  server/src/test/java/com/chutneytesting/admin/infra/DefaultDBVacuumTest.java
  server/src/test/java/util/infra/AbstractLocalDatabaseTest.java
  server/src/test/java/util/infra/EnableH2FileTestInfra.java
  server/src/test/java/util/infra/TestInfraConfiguration.java
  server/src/test/resources/test-infra/.gitignore
  server/src/test/resources/test-infra/h2-chutney-171.mv.db.blank.bak
  ui/src/app/core/services/database-admin.service.ts
  ui/src/app/modules/database-admin/components/database-admin.component.html
  ui/src/app/modules/database-admin/components/database-admin.component.ts
  ui/src/assets/i18n/en.json
  ui/src/assets/i18n/fr.json
Labels: technical

#1253 feat(server): Allow to save campaign with specific id
  server/src/main/java/com/chutneytesting/campaign/infra/CampaignJpaRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignEntity.java
  server/src/test/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepositoryTest.java
Labels: enhancement

#1252 feat(): On startup, reschedule missed campaign
  server/src/main/java/com/chutneytesting/SchedulingConfiguration.java
  server/src/main/java/com/chutneytesting/campaign/api/ScheduleCampaignController.java
  server/src/main/java/com/chutneytesting/campaign/domain/PeriodicScheduledCampaignRepository.java
  server/src/main/java/com/chutneytesting/campaign/infra/SchedulingCampaignFileRepository.java
  server/src/main/java/com/chutneytesting/execution/domain/schedule/CampaignScheduler.java
  server/src/test/java/com/chutneytesting/campaign/infra/PeriodicScheduledCampaignFileRepositoryTest.java
  server/src/test/java/com/chutneytesting/execution/domain/schedule/CampaignSchedulerTest.java
Labels: enhancement

#1254 Release 2.7.0
  CHANGELOG.md
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release

#1256 Prepare next development 2.7.1
  action-impl/pom.xml
  action-spi/pom.xml
  chutney-junit/api/pom.xml
  chutney-junit/engine/pom.xml
  chutney-junit/pom.xml
  engine/pom.xml
  environment/pom.xml
  glacio-adapter/pom.xml
  jira/pom.xml
  packaging/pom.xml
  pom.xml
  server-core/pom.xml
  server/pom.xml
  tools/pom.xml
  ui/pom.xml
Labels: release
