Repository chutney-testing/chutney, pull requests merged in 2024-03, with the labels that each got.

#18 feat(ui): right menu -> middle menu
  chutney/ui/src/app/core/components/parent/parent.component.html
  chutney/ui/src/app/modules/campaign/components/execution/history/campaign-executions-history.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.scss
  chutney/ui/src/app/shared/components/layout/right-menu/chutney-right-menu.component.html
  chutney/ui/src/app/shared/components/layout/right-menu/chutney-right-menu.component.scss
  chutney/ui/src/assets/style/themes/theme.darkly.scss
  chutney/ui/src/assets/style/themes/theme.flatly.scss
Labels: enhancement

#19 Clean JIRA service log
  chutney/jira/pom.xml
  chutney/jira/src/main/java/com/chutneytesting/jira/api/JiraModuleController.java
  chutney/jira/src/main/java/com/chutneytesting/jira/domain/JiraRepository.java
  chutney/jira/src/main/java/com/chutneytesting/jira/domain/JiraServerConfiguration.java
  chutney/jira/src/main/java/com/chutneytesting/jira/domain/JiraXrayClientFactory.java
  chutney/jira/src/main/java/com/chutneytesting/jira/domain/JiraXrayService.java
  chutney/jira/src/main/java/com/chutneytesting/jira/infra/HttpJiraXrayImpl.java
  chutney/jira/src/main/java/com/chutneytesting/jira/infra/JiraFileRepository.java
  chutney/jira/src/main/java/com/chutneytesting/jira/infra/JiraXrayFactoryImpl.java
  chutney/jira/src/test/java/com/chutneytesting/jira/api/JiraModuleControllerTest.java
  chutney/jira/src/test/java/com/chutneytesting/jira/api/JiraXrayEmbeddedApiTest.java
  chutney/jira/src/test/java/com/chutneytesting/jira/domain/JiraXrayServiceTest.java
  chutney/jira/src/test/java/com/chutneytesting/jira/infra/HttpJiraXrayImplTest.java
  chutney/server/src/main/java/com/chutneytesting/execution/domain/campaign/CampaignExecutionEngine.java
Labels: technical

#33 fix(server): getLastExecutions returns the last running exec if available, otherwise the last exec
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionJpaRepository.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
Labels: bug

#35 Chutney selenium action test - Use correct web driver output key
  chutney/action-impl/src/test/java/com/chutneytesting/action/selenium/SeleniumTest.java
Labels: technical

#37 Allow build with TestContainers' test for kotlin-dsl on docker in WSL2 without desktop
  kotlin-dsl/dsl/src/test/kotlin/blackbox/IntegrationTest.kt
  kotlin-dsl/dsl/src/test/kotlin/util/WSLUtil.kt
Labels: technical

#40 Throttle async scenario execution and SQLite routing r/w datasources example
  chutney/packaging/local-dev/src/main/java/com/chutneytesting/DBConfiguration.java
  chutney/packaging/local-dev/src/main/java/com/chutneytesting/DataSourceType.java
  chutney/packaging/local-dev/src/main/java/com/chutneytesting/TransactionRoutingDataSource.java
  chutney/packaging/local-dev/src/main/resources/application-db-sqlite-rw.yml
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
  chutney/server/src/main/java/com/chutneytesting/admin/infra/DefaultDBVacuum.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/CampaignExecutionDBRepository.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/DatabaseCampaignRepository.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/DatabaseTestCaseRepository.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  chutney/server/src/test/java/util/infra/AbstractLocalDatabaseTest.java
Labels: technical

#36 feat(server+ui): export campaign execution report as pdf
  chutney/server/src/main/java/com/chutneytesting/campaign/api/CampaignController.java
  chutney/server/src/main/java/com/chutneytesting/campaign/api/dto/CampaignExecutionFullReportDto.java
  chutney/server/src/main/java/com/chutneytesting/campaign/api/dto/CampaignExecutionReportMapper.java
  chutney/server/src/test/java/blackbox/SecuredControllerSpringBootIntegrationTest.java
  chutney/server/src/test/java/com/chutneytesting/campaign/api/CampaignControllerTest.java
  chutney/ui/package-lock.json
  chutney/ui/package.json
  chutney/ui/src/app/core/model/campaign/campaign-execution-report.model.ts
  chutney/ui/src/app/core/model/scenario/execution.model.ts
  chutney/ui/src/app/core/services/campaign-report.service.ts
  chutney/ui/src/app/core/services/campaign.service.ts
  chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.html
  chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.ts
Labels: enhancement

#39 fix(ui): Remove scroll on click
  chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
Labels: technical

#42 Regex does not work in github actions
  .github/workflows/release-github-template.yml
  .github/workflows/release-to-github.yml
  .github/workflows/release-to-ossrh.yml
Labels: technical

#43 Release 2.8.0
  CHANGELOG.md
  chutney/action-impl/pom.xml
  chutney/action-spi/pom.xml
  chutney/chutney-junit/api/pom.xml
  chutney/chutney-junit/engine/pom.xml
  chutney/chutney-junit/pom.xml
  chutney/engine/pom.xml
  chutney/environment/pom.xml
  chutney/glacio-adapter/pom.xml
  chutney/jira/pom.xml
  chutney/packaging/local-api-unsecure/pom.xml
  chutney/packaging/local-dev/pom.xml
  chutney/packaging/pom.xml
  chutney/pom.xml
  chutney/server-core/pom.xml
  chutney/server/pom.xml
  chutney/tools/pom.xml
  chutney/ui/pom.xml
  idea-plugin/gradle.properties
  kotlin-dsl/gradle.properties
Labels: release

#38 feat(server): enable offset reset before consuming from kafka
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/CustomConsumerRebalanceListener.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaBasicConsumeAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaConsumerFactoryFactory.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/EmbeddedKafkaBasicConsumeActionIntegrationTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionIntegrationTest.java
  chutney/action-impl/src/test/java/com/chutneytesting/action/kafka/KafkaBasicConsumeActionTest.java
  kotlin-dsl/dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyActionExtensions.kt
  kotlin-dsl/dsl/src/test/kotlin/com/chutneytesting/kotlin/dsl/ChutneyScenarioDslTest.kt
  kotlin-dsl/dsl/src/test/resources/dsl/kafka-actions.chutney.json
Labels: enhancement

#46 Scenario execution inherits scenario and dataset tags
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ExecutionRequest.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngine.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/ScenarioExecutionEngineAsync.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/history/ExecutionHistory.java
  chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/execution/report/ScenarioExecutionReport.java
  chutney/server-core/src/test/java/com/chutneytesting/server/core/domain/execution/ExecutionRequestTest.java
  chutney/server/src/main/java/com/chutneytesting/campaign/infra/jpa/CampaignEntity.java
  chutney/server/src/main/java/com/chutneytesting/execution/api/ExecutionSummaryDto.java
  chutney/server/src/main/java/com/chutneytesting/execution/api/ScenarioExecutionReportDto.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepository.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionEntity.java
  chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/jpa/ScenarioExecutionReportEntity.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/jpa/ScenarioEntity.java
  chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/TagListMapper.java
  chutney/server/src/main/resources/changelog/db.changelog-master.xml
  chutney/server/src/test/java/changelog/LiquibaseChangelogTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/api/report/surefire/SurefireCampaignExecutionReportBuilderTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/api/report/surefire/SurefireScenarioExecutionReportBuilderTest.java
  chutney/server/src/test/java/com/chutneytesting/execution/infra/storage/DatabaseExecutionHistoryRepositoryTest.java
  chutney/server/src/test/java/com/chutneytesting/scenario/infra/raw/TagListMapperTest.java
  chutney/server/src/test/java/util/infra/AbstractLocalDatabaseTest.java
  chutney/server/src/test/java/util/infra/TestInfraConfiguration.java
  chutney/server/src/test/resources/blackbox/application-db-h2.yml
  chutney/ui/src/app/core/model/scenario/execution.model.ts
  chutney/ui/src/app/modules/database-admin/components/database-admin.component.ts
  chutney/ui/src/app/modules/database-admin/components/resultReportList/database-admin-report-list.component.html
  chutney/ui/src/app/modules/database-admin/components/resultReportList/database-admin-report-list.component.scss
  chutney/ui/src/app/modules/database-admin/components/resultReportList/database-admin-report-list.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.html
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.scss
  chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.ts
  chutney/ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.ts
  chutney/ui/src/assets/i18n/en.json
  chutney/ui/src/assets/i18n/fr.json
Labels: enhancement

#47 fix(docs): broken links to code and img
  docs/docs/documentation/actions/index.md
  docs/docs/getting_started/write.md
  docs/docs/installation/ci_cd/scenario_sync.md
  docs/docs/installation/on_premise/minimal_conf.md
Labels: documentation

#44 Log kafka consume errors
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/KafkaBasicConsumeAction.java
  chutney/action-impl/src/main/java/com/chutneytesting/action/kafka/ListenerContainerErrorHandler.java
Labels: technical
